[package]
name = "joinn-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
joinn-dna = { path = "../joinn-dna" }
joinn-frame = { path = "../joinn-frame" }
joinn-live = { path = "../joinn-live" }
joinn-link = { path = "../joinn-link" }

[dev-dependencies]
joinn-prim = { path = "../joinn-prim" }
trybuild = "1.0"

[lints]
workspace = true
