//! All xtask command and helper functions.

mod admit_corpus_cells;
mod admit_lineage;
mod admit_sum_turn;
mod agree;
mod agree_cached;
mod allow_vocab_reason;
mod assay;
mod assay_idents;
mod budget_not_membrane;
mod calculator_success_trace;
mod check_vocab_fixtures;
mod controls_cross_matrix;
mod controls_fail_closed;
mod corpus_artifact;
mod corpus_has_no_carriage_returns;
mod corpus_rebless;
mod corpus_verify;
mod csr_no_hash;
mod decisions;
mod double_delivery;
mod drive_bound_zero;
mod drive_head;
mod first_desc_diff;
mod fixture_line;
mod floor;
mod g1_demo1;
mod g1_demo1_control;
mod g1_demo2;
mod g1_demo2_control;
mod g1_demo3;
mod g1_demo3_control;
mod g1_demo4;
mod g1_demo4_control;
mod g1_natives;
mod g2_alleles;
mod g2_alleles_control;
mod g2_bodies;
mod g2_bodies_control;
mod g2_evolution;
mod g2_evolution_control;
mod g2_turn;
mod g2_turn_control;
mod g3_artifacts;
mod g3_artifacts_control;
mod g3_descriptions;
mod g3_descriptions_control;
mod g3_hosts;
mod g3_hosts_control;
mod g3_intent;
mod g3_intent_control;
mod g3_run_gone;
mod g3_run_gone_control;
mod g3_signals;
mod g3_signals_control;
mod g3_transcript;
mod g3_transcript_control;
mod g3_value;
mod g3_value_control;
mod g51_frame;
mod g51_frame_control;
mod g51_hosts;
mod g51_hosts_control;
mod g51_tails;
mod g51_tails_control;
mod g51_total;
mod g51_total_control;
mod g52_bind;
mod g52_bind_control;
mod g52_ids;
mod g52_ids_control;
mod g52_refusal;
mod g52_refusal_control;
mod g5_assemble;
mod g5_assemble_control;
mod g5_exclusive;
mod g5_exclusive_control;
mod g5_law4;
mod g5_law4_control;
mod g5_lenses;
mod g5_lenses_control;
mod g5_linked;
mod g5_linked_control;
mod g5_locality;
mod g5_locality_control;
mod g5_membrane;
mod g5_membrane_control;
mod g5_revoke;
mod g5_revoke_control;
mod gate_all;
mod gate_five;
mod gate_five_items;
mod gate_five_one;
mod gate_five_one_items;
mod gate_five_two;
mod gate_five_two_items;
mod gate_one;
mod gate_one_items;
mod gate_three;
mod gate_three_items;
mod gate_two;
mod gate_two_items;
mod gate_two_one;
mod gate_two_one_items;
mod gate_two_two;
mod gate_two_two_items;
mod grade_opposed;
mod grant_order_not_arrival;
mod harness_fixtures;
mod hashes_path;
mod head_role;
mod int_val;
mod join_refuse_catches_drop;
mod line_has;
mod load_calculator;
mod load_phase5_bodies;
mod load_seals;
mod load_universe_file;
mod mask_std_calls;
mod membrane_field;
mod mutate;
mod nz;
mod one_delivery_path;
mod p21_agree;
mod p21_agree_control;
mod p21_findings;
mod p21_findings_control;
mod p21_pairing;
mod p21_pairing_control;
mod p21_trace;
mod p21_trace_control;
mod p21_transcript;
mod p21_transcript_control;
mod p21_turn;
mod p21_turn_control;
mod p21_turn_pair;
mod p21_v33;
mod p21_v33_control;
mod p21_wrapping;
mod p21_wrapping_control;
mod p22_bound;
mod p22_bound_control;
mod p22_corpus;
mod p22_corpus_control;
mod p22_lookup;
mod p22_lookup_control;
mod p22_path;
mod p22_path_control;
mod p22_register;
mod p22_register_control;
mod p22_roundtrip;
mod p22_roundtrip_control;
mod p22_see;
mod p22_see_control;
mod p22_true;
mod p22_true_control;
mod p22_v33;
mod p22_v33_control;
mod parse_body_ok;
mod parse_lock_scores;
mod parse_subject;
mod perf;
mod power;
mod power_phase2;
mod probe_refusal;
mod reference_add_steps;
mod refuse_false_law;
mod require_full;
mod resolve_named;
mod run_body_bin;
mod run_calculator_bin;
mod run_gate_table;
mod run_legacy_table;
mod scores_match;
mod subject;
mod synthetic_fifty;
mod text_val;
mod ungranted_is_refused;
mod units_after;
mod verify_phase2_bodies;
mod vocab;
mod walk_cells;
mod walk_rs;
mod witness;
mod workspace_root;
mod write_lock;
mod xtask_writes_findings;

pub(crate) use admit_corpus_cells::admit_corpus_cells;
pub(crate) use admit_lineage::admit_lineage;
pub(crate) use admit_sum_turn::admit_sum_turn;
pub(crate) use agree::agree;
pub(crate) use agree_cached::agree_cached;
pub(crate) use allow_vocab_reason::allow_vocab_reason;
pub(crate) use assay::{assay, assay_agree, assay_invariance};
pub(crate) use budget_not_membrane::budget_not_membrane;
pub(crate) use calculator_success_trace::calculator_success_trace;
pub(crate) use check_vocab_fixtures::check_vocab_fixtures;
pub(crate) use corpus_artifact::corpus_artifact;
pub(crate) use corpus_rebless::corpus_rebless;
pub(crate) use corpus_verify::corpus_verify;
pub(crate) use decisions::decisions;
pub(crate) use drive_bound_zero::drive_bound_zero;
pub(crate) use first_desc_diff::first_desc_diff;
pub(crate) use fixture_line::fixture_line;
pub(crate) use floor::floor;
pub(crate) use g1_demo1::g1_demo1;
pub(crate) use g1_demo1_control::g1_demo1_control;
pub(crate) use g1_demo2::g1_demo2;
pub(crate) use g1_demo2_control::g1_demo2_control;
pub(crate) use g1_demo3::g1_demo3;
pub(crate) use g1_demo3_control::g1_demo3_control;
pub(crate) use g1_demo4::g1_demo4;
pub(crate) use g1_demo4_control::g1_demo4_control;
pub(crate) use g1_natives::g1_natives;
pub(crate) use g2_alleles::g2_alleles;
pub(crate) use g2_alleles_control::g2_alleles_control;
pub(crate) use g2_bodies::g2_bodies;
pub(crate) use g2_bodies_control::g2_bodies_control;
pub(crate) use g2_evolution::g2_evolution;
pub(crate) use g2_evolution_control::g2_evolution_control;
pub(crate) use g2_turn::g2_turn;
pub(crate) use g2_turn_control::g2_turn_control;
pub(crate) use g3_artifacts::g3_artifacts;
pub(crate) use g3_artifacts_control::g3_artifacts_control;
pub(crate) use g3_descriptions::g3_descriptions;
pub(crate) use g3_descriptions_control::g3_descriptions_control;
pub(crate) use g3_hosts::g3_hosts;
pub(crate) use g3_hosts_control::g3_hosts_control;
pub(crate) use g3_intent::g3_intent;
pub(crate) use g3_intent_control::g3_intent_control;
pub(crate) use g3_run_gone::g3_run_gone;
pub(crate) use g3_run_gone_control::g3_run_gone_control;
pub(crate) use g3_signals::g3_signals;
pub(crate) use g3_signals_control::g3_signals_control;
pub(crate) use g3_transcript::g3_transcript;
pub(crate) use g3_transcript_control::g3_transcript_control;
pub(crate) use g3_value::g3_value;
pub(crate) use g3_value_control::g3_value_control;
pub(crate) use g5_assemble::g5_assemble;
pub(crate) use g5_assemble_control::g5_assemble_control;
pub(crate) use g5_exclusive::g5_exclusive;
pub(crate) use g5_exclusive_control::g5_exclusive_control;
pub(crate) use g5_law4::g5_law4;
pub(crate) use g5_law4_control::g5_law4_control;
pub(crate) use g5_lenses::g5_lenses;
pub(crate) use g5_lenses_control::g5_lenses_control;
pub(crate) use g5_linked::g5_linked;
pub(crate) use g5_linked_control::g5_linked_control;
pub(crate) use g5_locality::g5_locality;
pub(crate) use g5_locality_control::g5_locality_control;
pub(crate) use g5_membrane::g5_membrane;
pub(crate) use g5_membrane_control::g5_membrane_control;
pub(crate) use g5_revoke::g5_revoke;
pub(crate) use g5_revoke_control::g5_revoke_control;
pub(crate) use g51_frame::g51_frame;
pub(crate) use g51_frame_control::g51_frame_control;
pub(crate) use g51_hosts::g51_hosts;
pub(crate) use g51_hosts_control::g51_hosts_control;
pub(crate) use g51_tails::g51_tails;
pub(crate) use g51_tails_control::g51_tails_control;
pub(crate) use g51_total::g51_total;
pub(crate) use g51_total_control::g51_total_control;
pub(crate) use g52_bind::g52_bind;
pub(crate) use g52_bind_control::g52_bind_control;
pub(crate) use g52_ids::g52_ids;
pub(crate) use g52_ids_control::g52_ids_control;
pub(crate) use g52_refusal::g52_refusal;
pub(crate) use g52_refusal_control::g52_refusal_control;
pub(crate) use gate_all::{PHASE_LABELS, gate_all};
pub(crate) use gate_five::gate_five;
pub(crate) use gate_five_items::gate_five_items;
pub(crate) use gate_five_one::gate_five_one;
pub(crate) use gate_five_one_items::gate_five_one_items;
pub(crate) use gate_five_two::gate_five_two;
pub(crate) use gate_five_two_items::gate_five_two_items;
pub(crate) use gate_one::gate_one;
pub(crate) use gate_one_items::gate_one_items;
pub(crate) use gate_three::gate_three;
pub(crate) use gate_three_items::gate_three_items;
pub(crate) use gate_two::gate_two;
pub(crate) use gate_two_items::gate_two_items;
pub(crate) use gate_two_one::gate_two_one;
pub(crate) use gate_two_one_items::gate_two_one_items;
pub(crate) use gate_two_two::gate_two_two;
pub(crate) use gate_two_two_items::gate_two_two_items;
pub(crate) use grant_order_not_arrival::grant_order_not_arrival;
pub(crate) use harness_fixtures::harness_fixtures;
pub(crate) use hashes_path::hashes_path;
pub(crate) use int_val::int_val;
pub(crate) use join_refuse_catches_drop::join_refuse_catches_drop;
pub(crate) use line_has::line_has;
pub(crate) use load_calculator::load_calculator;
pub(crate) use load_phase5_bodies::load_phase5_bodies;
pub(crate) use load_seals::load_seals;
pub(crate) use load_universe_file::load_universe_file;
pub(crate) use mask_std_calls::mask_std_calls;
pub(crate) use nz::nz;
pub(crate) use one_delivery_path::one_delivery_path;
pub(crate) use p21_agree::p21_agree;
pub(crate) use p21_agree_control::p21_agree_control;
pub(crate) use p21_findings::p21_findings;
pub(crate) use p21_findings_control::p21_findings_control;
pub(crate) use p21_pairing::p21_pairing;
pub(crate) use p21_pairing_control::p21_pairing_control;
pub(crate) use p21_trace::p21_trace;
pub(crate) use p21_trace_control::p21_trace_control;
pub(crate) use p21_transcript::p21_transcript;
pub(crate) use p21_transcript_control::p21_transcript_control;
pub(crate) use p21_turn::p21_turn;
pub(crate) use p21_turn_control::p21_turn_control;
pub(crate) use p21_turn_pair::p21_turn_pair;
pub(crate) use p21_v33::p21_v33;
pub(crate) use p21_v33_control::p21_v33_control;
pub(crate) use p21_wrapping::p21_wrapping;
pub(crate) use p21_wrapping_control::p21_wrapping_control;
pub(crate) use p22_bound::p22_bound;
pub(crate) use p22_bound_control::p22_bound_control;
pub(crate) use p22_corpus::p22_corpus;
pub(crate) use p22_corpus_control::p22_corpus_control;
pub(crate) use p22_lookup::p22_lookup;
pub(crate) use p22_lookup_control::p22_lookup_control;
pub(crate) use p22_path::p22_path;
pub(crate) use p22_path_control::p22_path_control;
pub(crate) use p22_register::p22_register;
pub(crate) use p22_register_control::p22_register_control;
pub(crate) use p22_roundtrip::p22_roundtrip;
pub(crate) use p22_roundtrip_control::p22_roundtrip_control;
pub(crate) use p22_see::p22_see;
pub(crate) use p22_see_control::p22_see_control;
pub(crate) use p22_true::p22_true;
pub(crate) use p22_true_control::p22_true_control;
pub(crate) use p22_v33::p22_v33;
pub(crate) use p22_v33_control::p22_v33_control;
pub(crate) use parse_body_ok::parse_body_ok;
pub(crate) use parse_lock_scores::parse_lock_scores;
pub(crate) use perf::perf;
pub(crate) use power::power;
pub(crate) use power_phase2::power_phase2;
pub(crate) use probe_refusal::probe_refusal;
pub(crate) use reference_add_steps::reference_add_steps;
pub(crate) use refuse_false_law::refuse_false_law;
pub(crate) use require_full::require_full;
pub(crate) use resolve_named::resolve_named;
pub(crate) use run_body_bin::run_body_bin;
pub(crate) use run_calculator_bin::run_calculator_bin;
pub(crate) use run_gate_table::run_gate_table;
pub(crate) use run_legacy_table::run_legacy_table;
pub(crate) use scores_match::scores_match;
pub(crate) use synthetic_fifty::synthetic_fifty;
pub(crate) use text_val::text_val;
pub(crate) use ungranted_is_refused::ungranted_is_refused;
pub(crate) use units_after::units_after;
pub(crate) use verify_phase2_bodies::verify_phase2_bodies;
pub(crate) use vocab::vocab;
pub(crate) use walk_cells::walk_cells;
pub(crate) use walk_rs::walk_rs;
pub(crate) use witness::witness;
pub(crate) use workspace_root::workspace_root;
pub(crate) use write_lock::write_lock;
pub(crate) use xtask_writes_findings::xtask_writes_findings;

pub(crate) type LoadedSeals = (
    std::collections::BTreeMap<joinn_frame::Hash, joinn_dna::Body>,
    std::collections::BTreeMap<joinn_frame::Hash, joinn_dna::Cell>,
    Vec<joinn_prim::Seal>,
);
