[package]
name = "joinn-prim"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
joinn-dna = { path = "../joinn-dna" }
joinn-frame = { path = "../joinn-frame" }
joinn-gate = { path = "../joinn-gate" }
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"

[features]
mutants = []

[lints]
workspace = true
